### ISSUE TITLE
Remove the test target and re-add. It has the Podfile stuff

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/theFinalCountdown#3]

**Comment by AnnJohn** [comment]
@jmburges @markedwardmurray I'd like to icebox or close this one by tomorrow. Could you let me know if and which one is fine

**Comment by AnnJohn** [comment]
Iceboxing the issue

**Comment by markedwardmurray** [comment]
This has probably been resolved 0cb5135676ed0b6fa82c105378d08ac57d979b9f
